name: Bug report 🐞
description:
  Add a clear and concise description of the bug.
title: 'USWDS - Bug report: [YOUR TITLE]'
labels: ['wontfix', 'bug']
body:
  - type: markdown
    attributes:
      value: '## Bug Report'
  - type: textarea
    id: problem
    attributes:
      label: Describe the bug
      description: "Add a clear and concise description of the bug."
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: "Steps to reproduce the bug"
      description: |-
      1. Go to '...'
      2. Click on '....'
      3. Scroll down to '....'
      4. See error
    validations:
      required: true
  - type: textarea
    id: expectation
    attributes:
      label: "Expected behavior"
      description: "Add a clear and concise description of what you expected to happen."
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: "Add screenshots to help provide context, if applicable."
    validations:
      required: false
  - type: textarea
    id: system
    attributes:
      label: System setup
      description: "Include: USWDS version,
      Device,
      Operating system,
      Browser and version"
    validations:
      required: false
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: Please confirm the following
      options:
        - label:
            I agree to follow this project's [Code of
            Conduct](https://designsystem.digital.gov/about/community/#community-conduct).
          required: true
        - label:
            I checked the [current
            issues](https://github.com/uswds/uswds/issues?q=is%3Aissue+is%3Aopen+label%3A%22Type%3A+Bug%22) for
            duplicate feature requests.
          required: true
